<?php
/**
 * @file
 * A description of what your module does.
 */

/**
 * Implements hook_theme() to add the template definition.
 **/

/**
 * Implements hook_theme().
 */
function js_custom_header_theme($existing, $type, $theme, $path){
    $items['custom-header-block'] = array(
        'variables' => array(
            'textValue' => NULL,
        ),
        'path' => $path . '/templates',
    );

    return $items;
}